<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mozi [
  <!ELEMENT mozi (film*)>
  <!ELEMENT film (rendezo+, szinesz+, iro+)>
  <!ATTLIST film 
      id CDATA #REQUIRED
      mufaj (horror|sci-fi|romantikus) "horror"
  >
  <!ELEMENT rendezo (#EMPTY)>
  <!ATTLIST rendezo 
      id CDATA #REQUIRED
      nev CDATA #IMPLIED
  >
  <!ELEMENT szinesz (#EMPTY)>
  <!ATTLIST szinesz 
      id CDATA #REQUIRED
      nev CDATA #IMPLIED
  >
  <!ELEMENT iro (#EMPTY)>
  <!ATTLIST iro 
      id CDATA #REQUIRED
      nev CDATA #IMPLIED
  >
]>
<mozi>
  <film id="f1" mufaj="sci-fi">
    <rendezo id="r1">alex</rendezo>
    <szinesz id="s1">Madison_Ivy</szinesz>
    <iro id="i1"></iro>
  </film>
</mozi>
