=== SzSoma1/BK6QE8_XML/XMLTask_BK6QE8/2. Feladat/DOMParse_BK6QE8/src/hu/domparse/bk6qe8/XMLSchema_BK6QE8.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!--Egyszerű elemek-->

    <xs:element name="name" type="xs:string" />
    <xs:element name="type" type="ingredients_food_type" />
    <xs:element name="purchasePrice" type="xs:int" />
    <xs:element name="stockQuantity" type="xs:int" />
    
    <xs:element name="price" type="xs:int" />
    <xs:element name="description" type="xs:string" />

    <xs:element name="date" type="idoTipus" />
    <xs:element name="item" type="xs:string" />
    <xs:element name="status" type="status_type" />

    <xs:element name="orderingDate" type="idoTipus" />

    <xs:element name="postalcode" type="xs:int" />
    <xs:element name="street" type="xs:string" />
    <xs:element name="houseNumber" type="xs:int" />
    <xs:element name="doorNumber" type="xs:int" />
    <xs:element name="email" type="emailTipus" />
    <xs:element name="phoneNumber" type="telefonszamTipus" />

    <xs:element name="transportType" type="xs:string" />
    <xs:element name="isActive" type="xs:string" />

    <!--Saját típusok-->

    <xs:simpleType name="ingredients_food_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Base" />
            <xs:enumeration value="Sweetener" />
            <xs:enumeration value="Dairy" />
            <xs:enumeration value="Vegetable" />
            <xs:enumeration value="Meat" />
            <xs:enumeration value="Fish" />
            <xs:enumeration value="Pasta" />
            <xs:enumeration value="Italian" />
            <xs:enumeration value="Salad" />
            <xs:enumeration value="American" />
            <xs:enumeration value="Japanese" />
            <xs:enumeration value="Sushi" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="status_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Shipping" />
            <xs:enumeration value="Processing" />
            <xs:enumeration value="Completed" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="telefonszamTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="(06(20|30|31|50|60|70)\d{7})"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idoTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="([12]\d{3}.(0[1-9]|1[0-2]).(0[1-9]|[12]\d|3[01]))" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="emailTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[\w\.]+@([\w]+\.)+[\w]{2,4}" />
        </xs:restriction>
    </xs:simpleType>

    <!--Felépítés-->

    <xs:element name="Restaurant_BK6QE8">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ingredients" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="name" />
                            <xs:element name="type" />
                            <xs:element ref="purchasePrice" />
                            <xs:element ref="stockQuantity" />
                        </xs:sequence>
                        <xs:attribute name="ingredient_id" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="product" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="name" />
                            <xs:element ref="price" />
                            <xs:element ref="type" minOccurs="1" maxOccurs="unbounded"/>
                            <xs:element ref="description" />
                        </xs:sequence>
                        <xs:attribute name="product_id" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="made_of" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="ingredient_id" type="xs:int" />
                        <xs:attribute name="product_id" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="order" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="date" />
                            <xs:element ref="price" />
                            <xs:element ref="item" minOccurs="1" maxOccurs="unbounded" />
                            <xs:element ref="status" />
                        </xs:sequence>
                        <xs:attribute name="order_id" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="ordered_items" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="orderingDate" />
                        </xs:sequence>
                        <xs:attribute name="product_id" type="xs:int" />
                        <xs:attribute name="order_id" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="customer" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="name" />
                            <xs:element name="address" minOccurs="1" maxOccurs="1" >
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="postalcode" />
                                        <xs:element ref="street" />
                                        <xs:element ref="houseNumber" />
                                        <xs:element ref="doorNumber" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="phoneNumber" />
                            <xs:element name="email" />
                            <xs:element name="regularCustomer" />
                        </xs:sequence>
                        <xs:attribute name="customer_id" type="xs:int" />
                        <xs:attribute name="create_order" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="courier" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="name" />
                            <xs:element name="phoneNumber" />
                            <xs:element name="transportType" />
                            <xs:element name="isActive" />
                        </xs:sequence>
                        <xs:attribute name="courier_id" type="xs:int" />
                        <xs:attribute name="courier_demand" type="xs:int" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

        <!--Kulcsok-->

        <xs:key name="ingredient_kulcs">
            <xs:selector xpath="ingredients" />
            <xs:field xpath="@ingredient_id" />
        </xs:key>

        <xs:key name="product_kulcs">
            <xs:selector xpath="product" />
            <xs:field xpath="@product_id" />
        </xs:key>
        
        <xs:key name="order_kulcs">
            <xs:selector xpath="order" />
            <xs:field xpath="@order_id" />
        </xs:key>

        <xs:key name="customer_kulcs">
            <xs:selector xpath="customer" />
            <xs:field xpath="@customer_id" />
        </xs:key>

        <xs:key name="courier_kulcs">
            <xs:selector xpath="courier" />
            <xs:field xpath="@courier_id" />
        </xs:key>

        <!--Idegen kulcsok-->

        <xs:keyref refer="ingredient_kulcs" name="made_of_ingredient_idegen_kulcs">
            <xs:selector xpath="made_of" />
            <xs:field xpath="@ingredient_id" />
        </xs:keyref>

        <xs:keyref refer="product_kulcs" name="made_of_product_idegen_kulcs">
            <xs:selector xpath="made_of" />
            <xs:field xpath="@product_id" />
        </xs:keyref>

        <xs:keyref refer="order_kulcs" name="ordered_items_idegen_kulcs">
            <xs:selector xpath="ordered_items" />
            <xs:field xpath="@order_id" />
        </xs:keyref>

        <xs:keyref refer="order_kulcs" name="create_order_idegen_kulcs">
            <xs:selector xpath="customer" />
            <xs:field xpath="@create_order" />
        </xs:keyref>

        <xs:keyref refer="order_kulcs" name="courier_demand_idegen_kulcs">
            <xs:selector xpath="courier" />
            <xs:field xpath="@courier_demand" />
        </xs:keyref>

        <!--1:1-->

        <xs:unique name="create_order">
            <xs:selector xpath="customer" />
            <xs:field xpath="@create_order" />
        </xs:unique>

    </xs:element>

</xs:schema>

=== SzSoma1/BK6QE8_XML/XMLTask_BK6QE8/1. Feladat/XML_BK6QE8_toModify.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Restaurant_BK6QE8 xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchema_BK6QE8.xsd">

    <!--Ingredients-->

    <ingredients ingredient_id="1">
        <name>Flour</name>
        <type>Base</type>
        <purchasePrice>500</purchasePrice>
        <stockQuantity>1000</stockQuantity>
    </ingredients>
    
    <ingredients ingredient_id="2">
        <name>Honey</name>
        <type>Sweetener</type>
        <purchasePrice>800</purchasePrice>
        <stockQuantity>500</stockQuantity>
    </ingredients>
    
    <ingredients ingredient_id="3">
        <name>Cheese</name>
        <type>Dairy</type>
        <purchasePrice>400</purchasePrice>
        <stockQuantity>300</stockQuantity>
    </ingredients>
    
    <ingredients ingredient_id="4">
        <name>Tomatoes</name>
        <type>Vegetable</type>
        <purchasePrice>200</purchasePrice>
        <stockQuantity>400</stockQuantity>
    </ingredients>
    
    <ingredients ingredient_id="5">
        <name>Beef</name>
        <type>Meat</type>
        <purchasePrice>1500</purchasePrice>
        <stockQuantity>200</stockQuantity>
    </ingredients>

    <ingredients ingredient_id="6">
        <name>Salmon</name>
        <type>Fish</type>
        <purchasePrice>1800</purchasePrice>
        <stockQuantity>150</stockQuantity>
    </ingredients>  

    <!--Products-->

    <product product_id="1">
        <name>Spaghetti Bolognese</name>
        <price>2400</price>
        <type>Pasta</type>
        <description>Classic spaghetti with Bolognese sauce.</description>
    </product>
    
    <product product_id="2">
        <name>Greek Salad</name>
        <price>1800</price>
        <type>Salad</type>
        <description>A refreshing mix of cucumbers, tomatoes, olives, and feta cheese.</description>
    </product>
    
    <product product_id="3">
        <name>Grilled Salmon</name>
        <price>4000</price>
        <type>American</type>
        <description>Perfectly grilled salmon fillet with a side of saut√©ed tomatoes.</description>
    </product>

    <!--Made of kapcsolat-->

    <made_of ingredient_id="1" product_id="1"/>
    <made_of ingredient_id="4" product_id="1"/>
    <made_of ingredient_id="5" product_id="1"/>

    <made_of ingredient_id="4" product_id="2"/>
    <made_of ingredient_id="3" product_id="2"/>

    <made_of ingredient_id="6" product_id="3"/>
    <made_of ingredient_id="4" product_id="3"/>

    <!--Orders-->

    <order order_id="1">
        <date>2024.04.10</date>
        <price>4800</price>
        <item>Spaghetti Bolognese</item>
        <item>Greek Salad</item>
        <status>Completed</status>
    </order>
    
    <order order_id="2">
        <date>2024.05.20</date>
        <price>1800</price>
        <item>Greek Salad</item>
        <status>Processing</status>
    </order>
    
    <order order_id="3">
        <date>2024.06.15</date>
        <price>5800</price>
        <item>Grilled Salmon</item>
        <status>Shipping</status>
    </order>    

    <!--Order items kapcsolat-->

    <ordered_items order_id="1" product_id="1">
        <orderingDate>2024.04.10</orderingDate>
    </ordered_items>

    <ordered_items order_id="2" product_id="2">
        <orderingDate>2024.05.20</orderingDate>
    </ordered_items>

    <ordered_items order_id="3" product_id="3">
        <orderingDate>2024.06.15</orderingDate>
    </ordered_items>

    <!--Customers-->

    <customer create_order="1" customer_id="1">
        <name>Emma Brown</name>
        <address>
            <postalcode>90210</postalcode>
            <street>Elm Street</street>
            <houseNumber>12</houseNumber>
            <doorNumber>4</doorNumber>
        </address>
        <phoneNumber>+16505556789</phoneNumber>
        <email>emma.brown@example.com</email>
        <regularCustomer>true</regularCustomer>
    </customer>
    
    <customer create_order="2" customer_id="2">
        <name>Liam Davis</name>
        <address>
            <postalcode>10001</postalcode>
            <street>Broadway Avenue</street>
            <houseNumber>7</houseNumber>
            <doorNumber>1</doorNumber>
        </address>
        <phoneNumber>+14155552345</phoneNumber>
        <email>liam.davis@example.com</email>
        <regularCustomer>false</regularCustomer>
    </customer>
    
    <customer create_order="3" customer_id="3">
        <name>Olivia Taylor</name>
        <address>
            <postalcode>30303</postalcode>
            <street>Peachtree Street</street>
            <houseNumber>5</houseNumber>
            <doorNumber>3</doorNumber>
        </address>
        <phoneNumber>+17705556789</phoneNumber>
        <email>olivia.taylor@example.com</email>
        <regularCustomer>true</regularCustomer>
    </customer>

    <!--Couriers-->

    <courier courier_demand="1" courier_id="1">
        <name>James Wilson</name>
        <phoneNumber>+15555554321</phoneNumber>
        <transportType>Bicycle</transportType>
        <isActive>true</isActive>
    </courier>
    
    <courier courier_demand="2" courier_id="2">
        <name>Charlotte White</name>
        <phoneNumber>+14445555678</phoneNumber>
        <transportType>Car</transportType>
        <isActive>true</isActive>
    </courier>
    
    <courier courier_demand="3" courier_id="3">
        <name>Henry Moore</name>
        <phoneNumber>+13335556666</phoneNumber>
        <transportType>Motorcycle</transportType>
        <isActive>true</isActive>
    </courier>    

</Restaurant_BK6QE8>
